### ISSUE TITLE
能否将源码开源到mmdetection中？

### ISSUE THREAD

**Issue by 916968505** [yuantn/MI-AOD#1]
感觉代码结构和mmdetection很像，是不是合并以后传播度会更广？感谢！

**Comment by yuantn** [comment]
感谢您的建议，只是MIAL的这个代码主要是主动学习（Active Learning）领域的，检测只是其应用的一个具体领域。换句话说，我的MIAL的代码无法提高全监督情况下目标检测的性能，而mmdetection代码中都是一些像RetinaNet, Freeanchor, PAA等这种专门致力于提高检测性能的方法，所以感觉有些不太适宜。如果存在一些能够集成各种主动学习方法的代码库的话，我很愿意加入进去。谢谢！


袁天宁
2021-3-9








在 2021-03-08 15:00:42，"916968505" <notifications@github.com> 写道：

感觉代码结构和mmdetection很像，是不是合并以后传播度会更广？感谢！

**Comment by yuantn** [comment]
> 感觉代码结构和mmdetection很像，是不是合并以后传播度会更广？感谢！

对了，上面是我的回复，之前忘记引用了。
