### ISSUE TITLE
Compared with semi-supervision

### ISSUE THREAD

**Issue by czy341181** [yuantn/MI-AOD#12]
I would like to ask what is the difference between active learning and semi-supervision.

I am doing semi-supervised, I read the paper and the code and didn't find difference, 
Is active learning and semi-supervised the same thing？ Or What is the main difference between the two, and can I directly use active learning for semi-supervision？

**Comment by czy341181** [comment]
So after active learning to select those informative samples, you still need to humanly annotate it before next cycle?

**Comment by yuantn** [comment]
> So after active learning to select those informative samples, you still need to humanly annotate it before next cycle?

In actual industrial applications, the human labeling after each cycle is required. But in the experiment, we only need to enable the label and annotation of the "unlabeled" samples, because the annotations of all samples in the datasets are available.

**Comment by czy341181** [comment]
got it. Thanks for your patient reply!
