### ISSUE TITLE
Validaiton| TypeError: 'DataContainer' object is not subscriptable

### ISSUE THREAD

**Issue by chrissyguo** [yuantn/MI-AOD#14]
Encounter this error when procssessing validation
> [                                                  ] 0/4952, elapsed: 0s, ETA:Traceback (most recent call last):
  File "./tools/train.py", line 267, in <module>
    main()
  File "./tools/train.py", line 242, in main
    distributed=distributed, validate=args.no_validate, timestamp=timestamp, meta=meta)
  File "/home/bdggj/MI-AOD/mmdet/apis/train.py", line 120, in train_detector
    runner.run(data_loaders_L, cfg.workflow, cfg.total_epochs)
  File "/home/bdggj/anaconda3/envs/miaod/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 161, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/bdggj/anaconda3/envs/miaod/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 43, in train
    self.call_hook('after_train_epoch')
  File "/home/bdggj/anaconda3/envs/miaod/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 298, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/bdggj/MI-AOD/mmdet/core/evaluation/eval_hooks.py", line 71, in after_train_epoch
    gpu_collect=self.gpu_collect)
  File "/home/bdggj/MI-AOD/mmdet/apis/test.py", line 85, in multi_gpu_test
    y_head = model(return_loss=False, rescale=True, **data)
  File "/home/bdggj/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bdggj/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/bdggj/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bdggj/MI-AOD/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/bdggj/MI-AOD/mmdet/models/detectors/base.py", line 164, in forward
    return self.forward_test(x, img_metas, return_box=return_box, **kwargs)
  File "/home/bdggj/MI-AOD/mmdet/models/detectors/base.py", line 144, in forward_test
    return self.simple_test(imgs[0], img_metas[0], return_box=return_box, **kwargs)
  File "/home/bdggj/MI-AOD/mmdet/models/detectors/single_stage.py", line 109, in simple_test
    y_head_loc_cls = self.bbox_head.get_bboxes(*outs, img_metas, rescale=rescale)
  File "/home/bdggj/MI-AOD/mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/home/bdggj/MI-AOD/mmdet/models/dense_heads/MIAOD_head.py", line 641, in get_bboxes
    img_shape = img_metas[img_id]['img_shape']
TypeError: 'DataContainer' object is not subscriptable
Traceback (most recent call last):
  File "/home/bdggj/anaconda3/envs/miaod/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bdggj/anaconda3/envs/miaod/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bdggj/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/bdggj/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/bdggj/anaconda3/envs/miaod/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/bdggj/anaconda3/envs/miaod/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/MIAOD.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
Killing subprocess 30225

**Comment by yuantn** [comment]
You can debug it to see what the format of `img_metas` is. It may be solved by adding [0] after it, like this:
`img_shape = img_metas[0][img_id]['img_shape']`

**Comment by chrissyguo** [comment]
Thanks for your reply!

The format of `img_metas` is 'DataContainer'. FYI

` ETA:DataContainer([[{'filename': '/home/bdggj/Documents/data/voc/VOCdevkit/VOC2007/JPEGImages/000001.jpg', 'ori_filename': 'JPEGImages/000001.jpg', 'ori_shape': (500, 353, 3), 'img_shape': (850, 600, 3), 'pad_shape': (864, 608, 3), 'scale_factor': array([1.6997167, 1.7      , 1.6997167, 1.7      ], dtype=float32), 'flip': False, 'flip_direction': None, 'img_norm_cfg': {'mean': array([123.675, 116.28 , 103.53 ], dtype=float32), 'std': array([58.395, 57.12 , 57.375], dtype=float32), 'to_rgb': True}}]])`

I also tried `img_shape = img_metas[0][img_id]['img_shape']` but does not help.

I think this is a similar problem as #[https://github.com/open-mmlab/mmdetection/issues/1501](url)

But I do run this code on a GPU environment. 

I have never met this problem when I training with two-stage detectors using mmdetection.

**Comment by yuantn** [comment]
I've met similar problem, and I think you can try these solutions, which may be useful:

1. `img_shape = img_metas.data[img_id]['img_shape']`

2. `img_shape = img_metas['img_shape']`

3. try other methods to read DataContainer, such as `img_metas[0]`, `img_metas.data`, `img_metas.data[0]`, `img_metas[img_shape]` and so on.

Hope these can help you. (It's a pity that I cannot debug these days.)

**Comment by chrissyguo** [comment]
Thank you so much!
`img_metas.data[0]` can work!

**Comment by wuliacbd** [comment]
你好，我这个之前也报这个错误，然后我也改了，为什么还是有TypeError: 'DataContainer' object is not subscriptable问题

**Comment by yuantn** [comment]
你好，请提供你的输出日志，以及对应的 `img_metas` 打印结果。

---

Hello, please provide your output log, and the corresponding `img_metas` result printed.

**Comment by wuliacbd** [comment]
我在终端输入python tools/train.py  configs/MIAOD.py 运行没有问题，但是输入./script.sh 0时就有问题了

**Comment by yuantn** [comment]
> 我在终端输入python tools/train.py configs/MIAOD.py 运行没有问题，但是输入./script.sh 0时就有问题了

请提供你的输出日志。

---

Please provide your output log.

**Comment by wuliacbd** [comment]
[ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;] 0/4952, elapsed: 0s, ETA:Traceback (most recent call last):
&nbsp; File "./tools/train.py", line 257, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "./tools/train.py", line 232, in main
&nbsp; &nbsp; distributed=distributed, validate=args.no_validate, timestamp=timestamp, meta=meta)
&nbsp; File "/home/liugh/MI-AOD-master/mmdet/apis/train.py", line 120, in train_detector
&nbsp; &nbsp; runner.run(data_loaders_L, cfg.workflow, cfg.total_epochs)
&nbsp; File "/home/liugh/.conda/envs/miaod/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 161, in run
&nbsp; &nbsp; epoch_runner(data_loaders[i], **kwargs)
&nbsp; File "/home/liugh/.conda/envs/miaod/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 43, in train
&nbsp; &nbsp; self.call_hook('after_train_epoch')
&nbsp; File "/home/liugh/.conda/envs/miaod/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 298, in call_hook
&nbsp; &nbsp; getattr(hook, fn_name)(self)
&nbsp; File "/home/liugh/MI-AOD-master/mmdet/core/evaluation/eval_hooks.py", line 71, in after_train_epoch
&nbsp; &nbsp; gpu_collect=self.gpu_collect)
&nbsp; File "/home/liugh/MI-AOD-master/mmdet/apis/test.py", line 85, in multi_gpu_test
&nbsp; &nbsp; y_head = model(return_loss=False, rescale=True, **data)
&nbsp; File "/home/liugh/.conda/envs/miaod/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/liugh/.conda/envs/miaod/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
&nbsp; &nbsp; output = self.module(*inputs[0], **kwargs[0])
&nbsp; File "/home/liugh/.conda/envs/miaod/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/liugh/MI-AOD-master/mmdet/core/fp16/decorators.py", line 51, in new_func
&nbsp; &nbsp; return old_func(*args, **kwargs)
&nbsp; File "/home/liugh/MI-AOD-master/mmdet/models/detectors/base.py", line 164, in forward
&nbsp; &nbsp; return self.forward_test(x, img_metas, return_box=return_box, **kwargs)
&nbsp; File "/home/liugh/MI-AOD-master/mmdet/models/detectors/base.py", line 144, in forward_test
&nbsp; &nbsp; return self.simple_test(imgs[0], img_metas[0], return_box=return_box, **kwargs)
&nbsp; File "/home/liugh/MI-AOD-master/mmdet/models/detectors/single_stage.py", line 109, in simple_test
&nbsp; &nbsp; y_head_loc_cls = self.bbox_head.get_bboxes(*outs, img_metas, rescale=rescale)
&nbsp; File "/home/liugh/MI-AOD-master/mmdet/core/fp16/decorators.py", line 131, in new_func
&nbsp; &nbsp; return old_func(*args, **kwargs)
&nbsp; File "/home/liugh/MI-AOD-master/mmdet/models/dense_heads/MIAOD_head.py", line 636, in get_bboxes
&nbsp; &nbsp; img_shape = img_metas[img_id]['img_shape']
TypeError: 'DataContainer' object does not support indexing


这是./script.sh 0的结果，


然后在使用python直接运行的时候已经出了1k的结果了
[&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;] 4952/4952, 74.0 task/s, elapsed: 67s, ETA:&nbsp; &nbsp; &nbsp;0s2022-04-20 15:41:02,700 - mmdet - INFO -&nbsp;
+-------------+------+-------+--------+-------+
| class&nbsp; &nbsp; &nbsp; &nbsp;| gts&nbsp; | dets&nbsp; | recall | ap&nbsp; &nbsp; |
+-------------+------+-------+--------+-------+
| aeroplane&nbsp; &nbsp;| 285&nbsp; | 923&nbsp; &nbsp;| 0.779&nbsp; | 0.663 |
| bicycle&nbsp; &nbsp; &nbsp;| 337&nbsp; | 1090&nbsp; | 0.742&nbsp; | 0.612 |
| bird&nbsp; &nbsp; &nbsp; &nbsp; | 459&nbsp; | 2388&nbsp; | 0.643&nbsp; | 0.471 |
| boat&nbsp; &nbsp; &nbsp; &nbsp; | 263&nbsp; | 1780&nbsp; | 0.673&nbsp; | 0.422 |
| bottle&nbsp; &nbsp; &nbsp; | 469&nbsp; | 3348&nbsp; | 0.422&nbsp; | 0.217 |
| bus&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 213&nbsp; | 997&nbsp; &nbsp;| 0.836&nbsp; | 0.668 |
| car&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 1201 | 4420&nbsp; | 0.839&nbsp; | 0.727 |
| cat&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 358&nbsp; | 1036&nbsp; | 0.782&nbsp; | 0.643 |
| chair&nbsp; &nbsp; &nbsp; &nbsp;| 756&nbsp; | 6845&nbsp; | 0.663&nbsp; | 0.372 |
| cow&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 244&nbsp; | 1157&nbsp; | 0.738&nbsp; | 0.404 |
| diningtable | 206&nbsp; | 1333&nbsp; | 0.772&nbsp; | 0.568 |
| dog&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 489&nbsp; | 2055&nbsp; | 0.822&nbsp; | 0.630 |
| horse&nbsp; &nbsp; &nbsp; &nbsp;| 348&nbsp; | 1900&nbsp; | 0.865&nbsp; | 0.630 |
| motorbike&nbsp; &nbsp;| 325&nbsp; | 1340&nbsp; | 0.766&nbsp; | 0.626 |
| person&nbsp; &nbsp; &nbsp; | 4528 | 19870 | 0.810&nbsp; | 0.640 |
| pottedplant | 480&nbsp; | 2273&nbsp; | 0.442&nbsp; | 0.234 |
| sheep&nbsp; &nbsp; &nbsp; &nbsp;| 242&nbsp; | 1115&nbsp; | 0.645&nbsp; | 0.444 |
| sofa&nbsp; &nbsp; &nbsp; &nbsp; | 239&nbsp; | 1687&nbsp; | 0.824&nbsp; | 0.555 |
| train&nbsp; &nbsp; &nbsp; &nbsp;| 282&nbsp; | 1130&nbsp; | 0.819&nbsp; | 0.711 |
| tvmonitor&nbsp; &nbsp;| 308&nbsp; | 1912&nbsp; | 0.776&nbsp; | 0.593 |
+-------------+------+-------+--------+-------+
| mAP&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; | 0.542 |
+-------------+------+-------+--------+-------+
2022-04-20 15:41:02,866 - mmdet - INFO - Epoch [5][2000/2000]&nbsp; &nbsp;lr: 1.000e-04, mAP: 0.5415mAP: 0.5415






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianning ***@***.***&gt;; 
发送时间: 2022年4月20日(星期三) 下午3:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuantn/MI-AOD] Validaiton| TypeError: &#39;DataContainer&#39; object is not subscriptable (#14)





  
我在终端输入python tools/train.py configs/MIAOD.py 运行没有问题，但是输入./script.sh 0时就有问题了
  
请提供你的输出日志。
 
 
Please provide your output log.

**Comment by yuantn** [comment]
请提供你对应的 img_metas 打印结果。

---

Please your corresponding `img_metas` printed result.
