### ISSUE TITLE
AssertionError: Please specify at least one operation

### ISSUE THREAD

**Issue by chh6936** [yuantn/MI-AOD#17]
**AssertionError: Please specify at least one operation (save/eval/format/show the results / save the results) with the argument "--out", "--eval", "--format-only", "--show" or "--show-dir"**

The problem came up when I was running this step**_python tools/test.py $CONFIG_PATH $CKPT_PATH_**.
I want to know what is $CONFIG_PATH and what is $CKPT_PATH.
How should I solve this problem？Thanks!

**Comment by yuantn** [comment]
First, please add `--eval mAP` after `python tools/test.py $CONFIG_PATH $CKPT_PATH`.

And please refer to [here](../#train-and-test). That is:

> where $CONFIG_PATH should be replaced by the path of the config file in the configs folder (usually it would be configs/MIAOD.py)

> where $CKPT_PATH should be replaced by the path of the checkpoint file (*.pth) in the work_dirs folder after training.

That is to say, the full command should be:

`python  tools/test.py configs/MIAOD.py latest.pth --eval mAP`

where the `latest.pth` should be replaced by your actual checkpoint file.

Please notice, if you haven't trained the model before, please download the trained modeled following the instruction [here](../#models), and move the downloaded checkpoint file `latest.pth` to this MI-AOD repository.
