### ISSUE TITLE
How to run it on COCO Dataset?

### ISSUE THREAD

**Issue by gen0924** [yuantn/MI-AOD#18]
I have a problem, if i wante run it on coco dataset, if we need to fix the file<active_datasets.py>? because its way to get X_U and X_L only fix the standard VOC dataset.Hope for your reply,and if possible, could you provide the python file to fit the coco dataset? THX~

**Comment by yuantn** [comment]
Yes, it is necessary to fix the file `active_datasets.py` in your plan. However, I achieve it in another way.

I use the code [in this repository](https://github.com/KapilM26/coco2VOC) to transfer the COCO json annotation to PASCAL VOC xml annotation, and use COCO JPEG images as PASCAL VOC JPEG Images. In this way, the code for training generally remains, while the code for test can be replaced with the part of config files in mmdetection.

**Comment by gen0924** [comment]
OK～Thanks for your reply! if coco dataset can be convert to voc dataset successfully, it may works well to train the coco dataset. but, there need some fix on  active_datasets.py about [07 12]part， thanks you, i am already works on voc dataset,but now we need work on my own dataset with coco type! thank you!

**Comment by gen0924** [comment]
![image](https://user-images.githubusercontent.com/19650201/122375053-78481a00-cf95-11eb-9d85-0298f60d0262.png)
when i convert my own data to VOC， i met these error, how can i do?THX~

**Comment by yuantn** [comment]
Please wait. I am writing the instructions of training and test on MS COCO in this repository. I will tell you as soon as I finish it.

**Comment by yuantn** [comment]
> 
> 
> OK～Thanks for your reply! if coco dataset can be convert to voc dataset successfully, it may works well to train the coco dataset. but, there need some fix on active_datasets.py about [07 12]part， thanks you, i am already works on voc dataset,but now we need work on my own dataset with coco type! thank you!

The instruction of data preparation on MS COCO is ready [here](../tree/master/for_coco). Hope it will help you.

You can leave a message in this issue if you have any questions. I will be back tomorrow.

**Comment by gen0924** [comment]
THX for your reply! i have not verify your repo! but based on your reply before, i have convert to VOC type dataset, and works well.

**Comment by chh6936** [comment]
> THX for your reply! i have not verify your repo! but based on your reply before, i have convert to VOC type dataset, and works well.
I want to ask how did you solve the problem **IndexError: index 0 is out of bounds for dimension 0 with size 0** .
Can you help me? Thank you.

**Comment by chh6936** [comment]
I want to ask how did you solve the problem IndexError: index 0 is out of bounds for dimension 0 with size 0 .
Can you help me? Thank you.

> THX for your reply! i have not verify your repo! but based on your reply before, i have convert to VOC type dataset, and works well.

**Comment by chiran7** [comment]
> I want to ask how did you solve the problem IndexError: index 0 is out of bounds for dimension 0 with size 0 . Can you help me? Thank you.
> 
> > THX for your reply! i have not verify your repo! but based on your reply before, i have convert to VOC type dataset, and works well.

Dear Author,
Can you suggest a proper change in the configuration file for custom data? although it trains and converges the loss function, I am getting 0 detections (no predictions) on custom data for MIAOD_SSD.

**Comment by yuantn** [comment]
Sorry, I am not clear about your custom dataset. Please describe the error in detail.

**Comment by chiran7** [comment]
Thank you for your reply. For your reference, I have added descriptions
including screenshot of test (not showing any detections on custom data).
