### ISSUE TITLE
Performance comparison of active object detection methods

### ISSUE THREAD

**Issue by yesjuhyeong** [yuantn/MI-AOD#19]
Hello, I have a question about MI-AOD performance.

Looking at Fig. 5(a) in the paper, MI-AOD method is very good compared to other methods when trained with 5% of randomly selected images.
However, looking at (b) and (c), although MI-AOD is still a good method, there is no significant difference as (a) in the first cycle. Is there any special reason?

![mi-aod question](https://user-images.githubusercontent.com/48784913/122646122-9f9b1480-d158-11eb-9dee-7c6029b2c0ef.JPG)

**Comment by yuantn** [comment]
Hello, thanks for the question. Here are my explanations.

First, let's pay attention to the experimental settings in the paper.

For datasets:
For PASCAL VOC, there are 16551 images for training and select, and 4952 images for test.
For MS COCO, there are 117266 images for training and select, and 5000 images for test.

For detectors:
For RetinaNet, we train the model for 26 epochs.
For SSD, we train the model for 300 epochs.

Then the answer is ready.
In (a), the number of initial labeled samples is [16551*5.0%]=827, which is slightly less than 1000 initial labeled samples in (b). But the training epoch is 26 in (a), which is much less than 300 epochs in (b), although RetinaNet is ahead of SSD to a certain extent. The more data and epochs, the more fitting models, and the smaller difference between MI-AOD and other methods. Also, that is why MI-AOD has greater advantages in the early learning cycles.
Similarly, the number of initial labeled samples in (a) is [16551*5.0%]=827, which is less than [117266*2.0%]=2345. And notice that MS COCO is a more challenging dataset for more categories, denser objects, and larger scale variation. So the performances of MI-AOD and other methods in early learning cycles are not so satisfactory, as 2.0% of the labeled data is difficult to cover so many complex situations and challenges. Thus, the difference between the two lower performances will not be too much.

**Comment by yesjuhyeong** [comment]
Thank you. Your comment is very helpful!
