### ISSUE TITLE
关于如何进行单张图像的推理测试【计算不确定性，或返回bbox】

### ISSUE THREAD

**Issue by gen0924** [yuantn/MI-AOD#21]

**Comment by yuantn** [comment]
你好，你需要的功能已更新，请参见 [此处](../../blob/master/README_cn.md#训练与测试)。

---

Hi, the function you need has been updated. Please refer to [here](../../#train-and-test).

**Comment by gen0924** [comment]
谢谢您提供这样的代码，但是似乎在进行测试时候，出现如下图错误：
![图片](https://user-images.githubusercontent.com/19650201/122901898-95f3f580-d380-11eb-8a38-d8094570b0f2.png)
在用自己的数据集进行训练时，没有出现这样的问题，所以我需要如何调整呢？

**Comment by gen0924** [comment]
好像是我自己的代码和您更新后的存在一定差距，已更新最新镜像，测试通过！辛苦您的解答！祝好～
