### ISSUE TITLE
Numbers used in the plot

### ISSUE THREAD

**Issue by doobidoob** [yuantn/MI-AOD#25]
Hi @yuantn 

Thanks for your interesting work and the code!

I want to compare your work with others using SSD on PASCAL VOC.
But I cannot find the exact numbers used in Fig. 5(b) in your paper (CDAL and MI-AOD).
Could you share exact numbers (mean and standard deviation) used in Fig. 5(b), especially for MI-AOD and CDAL?
If you followed the LL4AL paper's experimental settings, you would have the mean and standard deviation for 3 trials.

I would appreciate if you could share the mean and standard deviation of CDAL and MI-AOD in Fig. 5(b).

Thank you!

**Comment by yuantn** [comment]
Hi @doobidoob

Thanks for your attention!

For exact numbers of mean, you can get it by scaling from picture pixels to curve coordinates on the graph. And that is the way I get the exact numbers of mean in CDAL and other works for SSD. You can also get them in MI-AOD and CDAL paper.

And the standard deviation of MI-AOD is as follows. I don't have that of CDAL. You can ask it from the author of CDAL.

|Number of Labeled Images|1k|2k|3k|4k|5k|6k|7k|8k|9k|10k|
|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
|Std of MI-AOD (%)|2.15 | 1.52 | 0.77 | 0.54 | 0.34 | 0.28 | 0.23 | 0.21 | 0.18 | 0.17

**Comment by doobidoob** [comment]
Hi @yuantn 

Thanks for your comment and sharing the standard deviation of MI-AOD.

Some readers like me can roughly get numbers of MI-AOD in Fig. 5(b), but it's hard to pinpoint exactly to two decimal places.
I'd like to cite your paper, but it's difficult to figure out the numbers.
Could you provide the numbers of MI-AOD used in Fig 5(b)?
Since MI-AOD is your suggestion method, I think there should be exact numbers.

Thank you!

**Comment by yuantn** [comment]
Hi @doobidoob 

The number of MI-AOD is as follows. For the performance of any other works in Fig. 5(b), please ask the author of CDAL. Those data I got is fitted and may not be accurate.

|Number of Labeled Images|1k|2k|3k|4k|5k|6k|7k|8k|9k|10k|
|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
|Performance of MI-AOD (%) |53.62|62.86|66.83|69.33|70.80|72.21|72.84|73.74|74.18|74.91|

**Comment by doobidoob** [comment]
Hi @yuantn 
Thank you very much! 👍
