### ISSUE TITLE
关于训练代码

### ISSUE THREAD

**Issue by BlueBlueFF** [yuantn/MI-AOD#26]
https://github.com/yuantn/MI-AOD/blob/master/tools/train.py#L170
训练代码这一行的目的是什么呢？ 我理解是会在第一次迭代中，训练流程是  Label数据训练-> label + unlabel训练-> label数据训练，在之后的迭代中是label + unlabel训练-> label数据训练， 是这样的流程吗

**Comment by yuantn** [comment]
是的，需要让第一次和最后一次迭代都是在 label 数据集上训练，以保证训练模型的稳定性。

---

Yes, it is necessary to train on the labeled set for the first and last epochs to ensure the stability of the training model.
