### ISSUE TITLE
MS COCO config

### ISSUE THREAD

**Issue by cvcvcvkd** [yuantn/MI-AOD#27]
hi, i'm trying to reproduce your MS COCO results, could you update the MS COCO configs?

Many thanks!

**Comment by yuantn** [comment]
Please refer to the last line in this [section](../#data-preparation)

**Comment by cvcvcvkd** [comment]
thanks a lot!

**Comment by cvcvcvkd** [comment]
one more questions, is there baseline methods (Core-set (ICLR 18), CDAL (ECCV 20)) implementation and config? Thanks

**Comment by yuantn** [comment]
These configuration files have not been provided yet, because this repository is for MI-AOD.

You can refer to [here](../../../ozansener/active_learning_coreset) for Core-set, and [here](../../../sharat29ag/CDAL) for CDAL.
