### ISSUE TITLE
unlabeled使用gt信息

### ISSUE THREAD

**Issue by leonzgtee** [yuantn/MI-AOD#28]
你好，MI-AOD的代码中的Unlabeled set也需要从dataset到dataloader，且在epoch_based_runner.py 70-74行涉及了对gt_bboxes和gt_labels的操作，与我理解的unlabeld set应该不使用gt信息有点出入，能否帮忙指点一下。

**Comment by yuantn** [comment]
请参见问题 #29。

---

Please refer to Issue #29.
