### ISSUE TITLE
unlabeled 数据使用gt信息

### ISSUE THREAD

**Issue by leonzgtee** [yuantn/MI-AOD#29]
你好，MI-AOD的代码中的Unlabeled set也需要从dataset到dataloader，且在epoch_based_runner.py 70-74行涉及了对gt_bboxes和gt_labels的操作，与我理解的unlabeld set应该不使用gt信息有点出入，能否帮忙指点一下。

**Comment by yuantn** [comment]
你好，这几行的操作是为了对 unlabeled set 的图像抹除定位信息，即使其所有的定位数据全部置为 -1。这样在 [这里的第 479 行](../blob/master/mmdet/models/dense_heads/MIAOD_head.py#L479) 和 [565 行](../blob/master/mmdet/models/dense_heads/MIAOD_head.py#L565) 计算涉及到 unlabeled set 的 loss 时，就可以通过判断其定位数据是否小于 0 决定是否将该 loss 反传（即乘 0 操作）。实际上，如果 loss 没有反传，则意味着是没有使用 unlabeled set 的 GT 信息的。

---

Hello, these lines are to remove the localization information of the images in the unlabeled set, which is to make all of their localization information as -1. In this way, [in Line 479 here](../blob/master/mmdet/models/dense_heads/MIAOD_head.py#L479) and [Line 565 here](../blob/master/mmdet/models/dense_heads/MIAOD_head.py#L565), when calculating the loss on the unlabeled set, we can judge whether the localization information is less than 0 to determine whether to backward propagate the loss (i.e., multiply by 0). In fact, if the loss is not back propagated, it means that the GT information of the unlabeled set is not used.

**Comment by leonzgtee** [comment]
好的，谢谢。如果我是使用完全无标注的数据作为unlabeled set的话，需要做哪些修改呢？

**Comment by leonzgtee** [comment]
好的，谢谢。如果我是使用完全无标注的数据作为unlabeled set的话，需要做哪些修改呢？

**Comment by yuantn** [comment]
你可以在这些无标注数据的标注信息中添加任意一个定位框（例如，该定位框坐标可为 [0,0,0,0]，类别归属为类别 1）。它们在实际训练过程中并不会被用到，因此可以任意添加。该定位框的标注格式需要和其他有标注数据的标注格式保持一致。之后，在无标注数据集的 txt 索引中加入该数据的文件名即可。

---

You can add any bounding box to the annotation of the unlabeled data (for example, the coordinates of the bounding box can be [0,0,0,0], and the class attribute is class 1). They will not be used in the actual training process, so they can be added arbitrarily. The annotation format of the bounding box needs to be consistent with that of other labeled data. After that, just add the file name of the unlabeled data to the txt index of the unlabeled data set.

**Comment by leonzgtee** [comment]
明白了，非常感谢回复！！
