### ISSUE TITLE
Question about changing backbone

### ISSUE THREAD

**Issue by bluvory** [yuantn/MI-AOD#30]
Hello, I have a question about changing the backbones.
I want to change the backbone retinanet to ssd.
( customize 3 just like you customized 1 to 2 according to the paper )

I tried customizing it, and the following error occurred. ( look at link4 )
TypeError: __init__() missing 1 required positional argument: 'input_size'

So when I deleted input_size, I got the following error.
NameError: name 'input_size' is not defined

model, train_cfg, test_cfg are well inputted.
How can I fix this?

1. https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/retinanet_r50_fpn.py
2. https://github.com/yuantn/MI-AOD/blob/master/configs/_base_/retinanet_r50_fpn.py
3. https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/ssd300.py
4. https://github.com/bluvory/kuaicv/blob/main/ssd_vgg_custom.py

**Comment by yuantn** [comment]
Have you modified Line 4~7 in `configs/MIAOD.py`?

The `'./_base_/retinanet_r50_fpn.py'` need to be replaced by your `ssd_vgg_custom.py`.

**Comment by bluvory** [comment]
yes I already fixed that

**Comment by yuantn** [comment]
What if you uncomment the Line 6 in link 4?

**Comment by bluvory** [comment]
If i uncomment it, this error occurs.
TypeError: init() missing 1 required positional argument: 'input_size'

**Comment by yuantn** [comment]
Can I have a look at your outermost configuration file (like `configs/MIAOD.py` instead of `configs/_base_/models/ssd300.py` )?

**Comment by bluvory** [comment]
handRL is our custom dataset and this file (hand2voc) has been changed to voc format.

https://github.com/bluvory/kuaicv/blob/main/MIAOD.py
https://github.com/bluvory/kuaicv/blob/main/handRL.py

**Comment by yuantn** [comment]
I think that maybe you should add or modify something in [this SSD+VOC configuration file](https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/ssd300_voc0712.py) to your MIAOD.py, such as train_pipeline, test_pipeline, and so on.

You can refer to the difference between MIAOD.py and [the RetinaNet+VOC configuration file](https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/retinanet_r50_fpn_1x_voc0712.py).

**Comment by bluvory** [comment]
I changed the [MIAOD.py](https://github.com/bluvory/kuaicv/blob/main/MIAOD_ssd.py) like this on your advice,
but the error continues because the ssd_vgg_custom.py has not changed.
TypeError: __init__() missing 1 required positional argument: 'input_size'

**Comment by yuantn** [comment]
It is really a confusing error... Could you provide your full output log?

**Comment by bluvory** [comment]
here, I put both cases of errors in this link.
(input_size=300 is in (ssd_vgg_custom.py)[https://github.com/bluvory/kuaicv/blob/main/ssd_vgg_custom.py]

https://github.com/bluvory/kuaicv/blob/main/error.py

**Comment by yuantn** [comment]
I think I have got the point of the problem, that is, you need to add `input_size=input_size` in the `model.backbone` (anywhere in Lines 11-16) in your [ssd_vgg_custom.py](../../../bluvory/kuaicv/blob/main/ssd_vgg_custom.py).

The deep reason is that, all of this MI-AOD repository is based on [MMDetection V2.3.0](../../../open-mmlab/mmdetection/tree/v2.3.0) but not [the latest version of MMDetection](../../../open-mmlab/mmdetection). There are some differences between these two versions.

**Comment by bluvory** [comment]
I got it. Thank you for your kind response.
Have a nice day :)

**Comment by abhigoku10** [comment]
@bluvory  cna you please share ur implementation with retinanet repo
