### ISSUE TITLE
When I am training my data, there is a StopIteration problem.

### ISSUE THREAD

**Issue by chh6936** [yuantn/MI-AOD#31]
I want to know which parameters need to be modified when training my datasets.
I trained with my own ten picture data, but there was a problem, as shown in the figure.
![2021-07-12 15-23-11屏幕截图](https://user-images.githubusercontent.com/83000030/125248022-2a20ff00-e326-11eb-8d0b-67bffaadcf10.png)
**I don't know whether my parameters are not modified correctly or the training data is small.**
Can you help me, please? Thank you.

**Comment by yuantn** [comment]
Did you train on multiple GPUs?

If yes, please refer to the third Q&A [here](../blob/master/docs/FAQ.md#training-and-test).

**Comment by chh6936** [comment]
I took this step **python tools/train.py configs/MIAOD.py**. The number of GPUs is not set. I don't know where the problem is.

**Comment by chh6936** [comment]
I selected 20 images of VOC datasets you used, which also caused this problem **StopIteration**. As shown in the figure above.

**Comment by chh6936** [comment]
OK. Thank you! I will have a try.

**Comment by chh6936** [comment]
I increased the number of images. **StopIteration** has been solved. 
But I have a new problem, I want to know what **epoch_ratio = [3, 1]** means in configs/MIAOD.py.
Can I change it to epoch_ratio = [3, 0]？ Thank you!

**Comment by yuantn** [comment]
Please refer to [here](../tree/master/configs#unique-mi-aod-settings) for config explanations.

If you change it to [3, 0], there will not be maximizing and minimizing uncertainty.

**Comment by chh6936** [comment]
But this problem occurs when I use epoch_ratio = [3, 1]. As is shown in the figure.
![2021-07-16 14-57-14屏幕截图](https://user-images.githubusercontent.com/83000030/125905787-82270479-e32e-4862-b95e-22b41a49475d.png)

**Comment by yuantn** [comment]
Can you set a breakpoint there and print `y_loc_img`, `y_loc_img[0]`, `y_loc_img[0][0]` and `y_loc_img[0][0][0]`?

**Comment by chh6936** [comment]
ok. I **print (y_loc_img[0][0][0], y_loc_img[0][0], y_loc_img[0], y_loc_img)**.As is shown in the figure. I do not find the problem. Can you help me ?
![2021-07-16 21-04-21屏幕截图](https://user-images.githubusercontent.com/83000030/125953962-bdb0dd4f-8ac7-4f05-b130-81fb5fd96ba0.png)
![2021-07-16 21-03-57屏幕截图](https://user-images.githubusercontent.com/83000030/125953963-dd4ecb28-f63e-42d6-a582-eb74dae1989e.png)
![2021-07-16 21-03-35屏幕截图](https://user-images.githubusercontent.com/83000030/125953967-a1da1df9-1ed2-40ee-9dea-716fe115bd76.png)
![2021-07-16 21-03-11屏幕截图](https://user-images.githubusercontent.com/83000030/125953971-0d7ea214-93c2-4a53-be6f-59ff7fb2d4eb.png)

**Comment by chh6936** [comment]
ok. I print (y_loc_img[0][0][0], y_loc_img[0][0], y_loc_img[0], y_loc_img).As is shown in the figure. I do not find the problem. Can you help me ?
![2021-07-16 21-03-11屏幕截图](https://user-images.githubusercontent.com/83000030/125954140-8769fafc-ee99-45c0-ac6f-a38811dcb4d4.png)
![2021-07-16 21-03-35屏幕截图](https://user-images.githubusercontent.com/83000030/125954150-3bbc607f-02a9-421e-baf1-c1dde9d04fde.png)
![2021-07-16 21-03-57屏幕截图](https://user-images.githubusercontent.com/83000030/125954163-cc8b97f5-1753-4cb8-899c-78f245ac2854.png)
![2021-07-16 21-04-21屏幕截图](https://user-images.githubusercontent.com/83000030/125954183-28a88464-5c04-4449-bc5c-7c5c786e519a.png)

**Comment by chh6936** [comment]
I noticed that **#18** also had this problem **IndexError: index 0 is out of bounds for dimension 0 with size 0** with VOC datasets,  but in the end he said it worked well. I would like to know how to solve this problem. Thank you very much for your prompt reply.

**Comment by yuantn** [comment]
Unfortunately, I can’t tell which are `y_loc_img[0][0]` and which are `y_loc_img[0][0][0]` from your results.

If you can output these variable separately and independently, and tell me the correspondence between the variable names and variable values, it will be more clear and will not be so confusing.

And a possible solution can be changing 

```python
if y_loc_img[0][0][0] < 0:
```

in Line 479 in `L_wave_min` in `mmdet/models/dense_heads/MIAOD_head.py` to:

```python
if y_loc_img[0][0] < 0:
```

**Comment by chh6936** [comment]
ok. I reprinted **y_loc_img[0][0][0]** and **y_loc_img[0][0].**
The first picture is y_loc_img[0][0][0].
![1](https://user-images.githubusercontent.com/83000030/128634768-e69996b1-30e0-416d-8a65-6c6a2522d69d.png)
The second picture is y_loc_img[0][0].
![2](https://user-images.githubusercontent.com/83000030/128634817-7b528479-df02-4070-bbf8-8d3809440b10.png)
These two pictures are arranged after I print them out.
Does it help solve the problem **IndexError: index 0 is out of bounds for dimension 0 with size 0**

**Comment by chh6936** [comment]
ok. I reprinted **y_loc_img[0][0][0]** and **y_loc_img[0][0].**
The first picture is y_loc_img[0][0][0].
![1](https://user-images.githubusercontent.com/83000030/128634961-1d485e7f-0053-4cc2-9fdc-c1120a2e43f9.png)
The second picture is y_loc_img[0][0].
![3](https://user-images.githubusercontent.com/83000030/128635097-efa725dc-8b26-4c86-9508-d1b70a9dfad3.png)
These two pictures are arranged after I print them out.
Does it help solve the problem **IndexError: index 0 is out of bounds for dimension 0 with size 0**?

**Comment by yuantn** [comment]
They seems normal. The reason may be that some data is normal, but some is abnormal.

Can you insert an exception detection in the error line and print the `y_loc_img[0][0][0]` and `y_loc_img[0][0]` __only when the error occurs__?

**Comment by chh6936** [comment]
I changed the training data, but the problem **IndexError: index 0 is out of bounds for dimension 0 with size 0** still appeared after running for a while. I want to know how to know which data is the problem. Thank you.

**Comment by yuantn** [comment]
What I mean is that, your `y_loc_img[0][0][0]` and `y_loc_img[0][0]` is normal when it is being output, but it doesn't mean that it is always normal. So can you insert an exception detection in the error line and print `y_loc_img[0][0][0]` and `y_loc_img[0][0]` __only at that time__?

**Comment by yuantn** [comment]
You can use PyCharm to insert an exception detection, or directly use the following code:

```python
try:
    # copy your error line here
except:
    print y_loc_img[0][0][0]
    print y_loc_img[0][0]
```

**Comment by chh6936** [comment]
OK.Thank you very much for your patience in answering many of my questions. The problem has been solved.
