### ISSUE TITLE
How to run using SSD model

### ISSUE THREAD

**Issue by Liang-ZX** [yuantn/MI-AOD#33]
请问是否有提供使用SSD网络的代码，以及对应的预训练模型是什么，文章中好像没有谈

**Comment by yuantn** [comment]
使用 SSD 网络的代码正在整理中，对应的预训练模型为 `open-mmlab` 提供的 `vgg16_caffe` 模型。

---

The code for using the SSD network is being arranged, and the corresponding pre-trained model is the `vgg16_caffe` model provided by `open-mmlab`.

**Comment by yuantn** [comment]
使用 SSD 检测器的代码已经整理完毕，你可以更新这个目录（重新下载或重新克隆），并参考 [这里](../blob/master/README_cn.md#数据集准备) 关于使用 SSD 检测器的说明来实现在 SSD 检测器基础上的训练。

---

The code for using the SSD detector is ready, you can update this directory (re-download or re-clone), and refer to [here](../#data-preparation) for the instruction of using the SSD detector to implement the training based on the SSD detector.

**Comment by Liang-ZX** [comment]
感谢你的更新，另外我想再请问我的Retinanet for COCO的实验结果不如文章中的结果（PASCAL VOC基本相当），想请问你是用这个代码进行测试的吗？实验结果见下方截图。

另外，你的SSD的代码的epoch数似乎与文章中阐明的100并不一致，那么我想请问一下random的结果，你的实验设置是怎样的？打扰了，再次感谢。

祝顺利



-----Original Messages-----
From:"Tianning Yuan" ***@***.***>
Sent Time:2021-08-09 12:45:50 (Monday)
To: yuantn/MI-AOD ***@***.***>
Cc: Liang-ZX ***@***.***>, Author ***@***.***>
Subject: Re: [yuantn/MI-AOD] How to run using SSD model (#33)






使用 SSD 检测器的代码已经整理完毕，你可以更新这个目录（重新下载或重新克隆），并参考 这里 关于使用 SSD 检测器的说明来实现在 SSD 检测器基础上的训练。

The code for using the SSD detector is ready, you can update this directory (re-download or re-clone), and refer to here for the instruction of using the SSD detector to implement the training based on the SSD detector.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuantn** [comment]
首先，我的 RetinaNet for COCO 的实验确实是用当前代码库中的代码实现的，但我并不能看到你上传的截图。

另外，我在论文中从未声明 SSD 的 epoch 数为 100，反而是 300（240+60，如论文 4.1 节所述）。对于 random 的结果，我是去掉了所有在未标注集合上训练的过程，并以随机的方式挑选图像得出的结果。

---

First, the experiment of RetinaNet for COCO is indeed implemented with the code in the repository, but I cannot see the screenshot you uploaded.

In addition, I have not declared in the paper that the epoch number of SSD is 100, but 300 (240+60, as described in section 4.1 of the paper). For the random result, I removed all the training process on the unlabeled set, and selected the image randomly.
