### ISSUE TITLE
Loss is nan

### ISSUE THREAD

**Issue by 994374821** [yuantn/MI-AOD#34]
作者，您好！

当我使用自己数据集测试您代码时，l_det_loc、L_det损失是 nan，l_imgcls一直是0

自己测试集只有行人类，已经修改过datasets/voc.py中的CLASSES=('person',)

训练时使用的1个显卡

**Comment by yuantn** [comment]
你好，请参见问题 #24，看看能否解决你的问题。

---

Hello, please refer to Issue #24, and see if it can solve your problem.
