### ISSUE TITLE
Loss is nan

### ISSUE THREAD

**Issue by 994374821** [yuantn/MI-AOD#35]
作者，您好！

当我使用自己数据集测试您代码时，l_det_loc、L_det损失是 nan，l_imgcls一直是0

自己数据集只有行人类，已经修改过datasets/voc.py中的CLASSES=('person',)

训练时使用的1个显卡

**Comment by yuantn** [comment]
你好，请参见问题 #24，看看能否解决你的问题。

---

Hello, please refer to Issue #24, and see if it can solve your problem.

**Comment by 994374821** [comment]
将模型类别改为2（实际GT只有一类），l_imgcls正常了，但是l_det_loc、L_det损失依旧是 nan

**Comment by yuantn** [comment]
你可以看看你的数据集本身的边界框标注信息是否有问题，或者尝试调整学习率，并重新做一下实验，看看实验结果。

---

You can see if there is any problem with the bounding box annotation of your datasets, or try to adjust the learning rate, and re-run the experiment to check the experiment results.

**Comment by 994374821** [comment]
已解决，排查是因为标签问题
