### ISSUE TITLE
Comparison with other active learning methods

### ISSUE THREAD

**Issue by schubertm** [yuantn/MI-AOD#43]
Hi,

you compared your method with 2 baselines (random, entropy) and 2 other approaches (Core-set, CDAL) and you outperformed all of them.  The code with your query function is running but where in the code can i find the 4 other query functions to compare them with your approach for my own dataset?

Thanks in advance :)

**Comment by yuantn** [comment]
The code with 2 baselines (random and entropy) is easy to implement. You only need to modify the function [`calculate_uncertainty`](../blob/master/mmdet/apis/test.py#L15) in `mmdet/apis/test.py`.

For 2 other approaches (Core-set and CDAL), please refer to [here](https://github.com/ozansener/active_learning_coreset) (Core-set) and [here](https://github.com/sharat29ag/CDAL) (CDAL).

It should be noted that all other methods do not use the two adversarial classifiers and the MIL classifier.
