### ISSUE TITLE
作者您好，我想使用50%的数据量测试模型的mAP，该如何设置呢？

### ISSUE THREAD

**Issue by coldlarry** [yuantn/MI-AOD#46]
作者您好，非常感谢您的工作。您使用20%的数据量在VOC上达到了不错的效果，如果我想测试50%的数据量是否可以达到100%数据量的效果，我该怎么修改程序呢？

我粗略看了下代码，是不是只需要增加circle的值就可以了呢？

麻烦您回复下我~

**Comment by yuantn** [comment]
你好，你可以通过修改 [`configs/MIAOD.py`](../blob/master/configs/MIAOD.py) 中的初始已标注集大小 [`X_L_0_size`](../blob/master/configs/MIAOD.py#L44) 、每一个循环增加的已标注样本数量 [`X_S_size`](../blob/master/configs/MIAOD.py#L43) 和循环数 [`cycles`](../blob/master/configs/MIAOD.py#L46) 来达到你想要的效果。最后一个循环使用的已标注样本数据量等于 `X_L_0_size + X_S_size * (len(cycles) - 1)`。

---

Hello, you can modify the size of initial labeled set [`X_L_0_size`](../blob/master/configs/MIAOD.py#L44), the number of added labeled samples after each cycle [`X_S_size`](../blob/master/configs/MIAOD.py#L43) and the number of cycles [`cycles`](../blob/master/configs/MIAOD.py#L46) in [`configs/MIAOD.py`](../blob/master/configs/MIAOD.py) to achieve the effect you want. The amount of labeled data in the last cycle is `X_L_0_size + X_S_size * (len(cycles)-1)`.

**Comment by coldlarry** [comment]
感谢！这回答对我帮助很大。
