### ISSUE TITLE
多卡训练，精度大幅度下降

### ISSUE THREAD

**Issue by coldlarry** [yuantn/MI-AOD#47]
作者您好，我使用多卡训练（4张），并且增大了你设置的默认单卡bathsize。

训练时，第一次测试mAP接近0.（单卡训练时，第一次一般是0.6）。

想请教一下，这是什么原因呀？是学习率的问题吗？

**Comment by coldlarry** [comment]
单卡训练，调大batchsize，精度也会显著下降。这是为啥呀..................

**Comment by hongyanghu** [comment]
你好，我想询问您一下关于AutoSlim的问题，实在是找不到合适的联系方式。此处留下我的QQ：997739480

**Comment by yuantn** [comment]
> 
> 
> 你好，我想询问您一下关于AutoSlim的问题，实在是找不到合适的联系方式。此处留下我的QQ：997739480

你好，你可以再开一个新的 Issue 提问，但我不是很了解有关 AutoSlim 的知识。
---
Hello, you can open a new Issue, but I don’t know much about AutoSlim.
