### ISSUE TITLE
low performance about SSD on PASCAL VOC compared to paper

### ISSUE THREAD

**Issue by Liang-ZX** [yuantn/MI-AOD#49]
![image](https://user-images.githubusercontent.com/42173433/139160713-7c8fd100-8abb-4c98-9234-eabee37b8260.png)
如图，SSD on PASCAL VOC上的复现结果，与文章相比有明显下降，甚至不如random，想知道是否有其它同学也尝试复现，结果如何？

As shown in the figure, the reproduction results on SSD on Pascal VOC are significantly lower than those in the paper, and even worse than "random". I want to know whether other students also try to reproduce, and what are the results? Thank you!

**Comment by jiahao12121** [comment]
我和您一样的结果，我比对了作者log日志文件的参数，都是一致的。区别是我和楼主使用的都是单卡，也只能复现出不到70的mAP，很奇怪！
