### ISSUE TITLE
Don't seem to have frozen the parameters of the regression header?

### ISSUE THREAD

**Issue by shnew** [yuantn/MI-AOD#51]
Thank you very much for your work. It's very valuable. I have a question: In the process of re-weighting and minimizing instance uncertainties, you don't seem to have frozen the parameters of the regression header?

**Comment by yuantn** [comment]
Please refer to Line 185-191 in [`tools/train.py`](../blob/master/tools/train.py#L185).

**Comment by shnew** [comment]
Thank you for your answer !
