### ISSUE TITLE
能否在Windows系统下运行呢？

### ISSUE THREAD

**Issue by Sageeeeeee** [yuantn/MI-AOD#52]
作者你好，我按照install中的指示尝试在Windows系统下配置环境，发现1、pip install mmcv-full=1.0.5命令会报错，只能用pip install mmcv代替，不知道两者有什么区别，会不会有影响；2、修改mmcv包命令cp是linux平台的命令所以也会报错。所以就想问的是是否有在Windows平台下运行的方法，还是说根本不支持在Windows平台下运行呢？

**Comment by yuantn** [comment]
I have tried to install only `mmcv` before, but it didn't work successfully. MMDetection officially requires the installation of `mmcv-full` (see step c in [here](https://github.com/open-mmlab/mmdetection/blob/v2.3.0/docs/install.md#install-mmdetection)) For the difference between `mmcv` and `mmcv-full`, you can refer to [here](https://github.com/open-mmlab/mmcv#installation).
The purpose of modifying the `mmcv` package is to replace the files in the corresponding location. `cp -v $A $B` means to copy the files in location A to location B, so you can modify it correspondingly. But our code is modified on the basis of [MMDetection v2.3.0](https://github.com/open-mmlab/mmdetection/tree/v2.3.0), it does not support running on the Windows platform (see the first requirement in [here](https://github.com/open-mmlab/mmdetection/blob/v2.3.0/docs/install.md#requirements)).

---

我之前曾经尝试过仅安装 `mmcv`，但没有成功运行。MMDetection 官方也要求安装 `mmcv-full`（参见 [这里](https://github.com/open-mmlab/mmdetection/blob/v2.3.0/docs/install.md#install-mmdetection) 的步骤 c） 关于 `mmcv` 和 `mmcv-full` 的区别你可以参见 [这里](https://github.com/open-mmlab/mmcv/blob/master/README_zh-CN.md)。
修改 `mmcv` 包的目的是替换其中对应位置的文件，`cp -v $A $B` 的意思是将 A 位置的文件复制到 B 处，所以你可以对应地进行修改。但我们的代码是在 [MMDetection v2.3.0](https://github.com/open-mmlab/mmdetection/tree/v2.3.0) 的基础上修改的，它并不支持在 Windows 平台上运行（参见 [这里](https://github.com/open-mmlab/mmdetection/blob/v2.3.0/docs/install.md#requirements) 的第一个需求项）。
