### ISSUE TITLE
active_datasets.py中X_U的选取

### ISSUE THREAD

**Issue by ChenggangLu** [yuantn/MI-AOD#56]
`
    X_U = X_all[-cfg.X_L_0_size:].copy()
`
您好,请问这里未标注数据的选取是不是多了一个负号?

**Comment by yuantn** [comment]
We need to train classifiers on the labeled and unlabeled samples, so we select unlabeled samples equal to the size of the labeled set in each active learning cycle. The negative sign here is to select an equal sample subset from all unlabeled samples for subsequent model training and sample selection.

---

因为我们需要将两个分类器在已标注样本和未标注样本上均进行训练，所以我们在每个主动学习周期中针对于已标注样本集的大小，选取等量的未标注样本。这里的负号即为在所有的未标注样本中选取等量的样本子集，以进行后续的训练与样本选择。
