### ISSUE TITLE
Extend it to use other mmdetection models

### ISSUE THREAD

**Issue by danishnazir** [yuantn/MI-AOD#57]
Thanks for the amazing work, I wanted to ask if we can extend the proposed model to use with mmdetection models e.g. faster-rcnns etc. Will simply replacing and managing the config files work? or the method is specifically designed to work with refineNet and SSD?

**Comment by yuantn** [comment]
Thanks for your attention to our work.
This model can be extended to more mmdetection models. Extending to the anchor-based models would be easier, but just replacing the configuration files is not enough.

You can regard this repository as a basic version for RetinaNet and an improved version for SSD, and check which files are specially modified for SSD refer to the section [Code Structure](https://github.com/yuantn/MI-AOD#code-structure) (such as `configs/_base_/ssd300.py`, `configs/MIAOD_SSD.py`, `mmdet/models/dense_heads/__init__.py`, `mmdet/models/dense_heads/ssd_head.py`, etc.). Then you can add and modify the corresponding code of the model you want to extend.

Of course, if the model you want to extend is a two-stage detection model like faster-RCNN, you also need to pay attention to the modification of the files like `mmdet/models/detectors/two_stage.py`, which are only applicable to two-stage models.

---

感谢您对本工作的关注。

该模型可以扩展至更多的 mmdetection 模型。扩展到基于锚框的方法会较为容易一些，但仅仅替换配置文件是不够的。

你可以将本代码库看作一个适用于 RetinaNet 的基本版和适用于 SSD 的改进版，并参考在 [代码结构](https://github.com/yuantn/MI-AOD/blob/master/README_cn.md#代码结构) 部分对比有哪些文件针对 SSD 特意进行了改动（如 `configs/_base_/ssd300.py`、`configs/MIAOD_SSD.py`、`mmdet/models/dense_heads/__init__.py`、`mmdet/models/dense_heads/ssd_head.py`等等），并将你想要扩展到的模型进行对应部分代码的添加与修改即可。

当然如果你要扩展到的模型是类似于 faster-RCNN 的双阶段检测网络的话，你也需要注意一下对 `mmdet/models/detectors/two_stage.py` 类似仅适用于双阶段网络文件的修改。
