### ISSUE TITLE
pip install -v -e  . 报错

### ISSUE THREAD

**Issue by jiahao12121** [yuantn/MI-AOD#59]
前面都比较顺利，编译mmdetection的时候下载pycocotools会报错，连接不上那个仓库？
![image](https://user-images.githubusercontent.com/32212571/154628912-f2838776-a367-492b-b108-84920ad5d32a.png)

![image](https://user-images.githubusercontent.com/32212571/154629007-89af010c-f173-4ab2-8bc9-f21d39a387ae.png)

后来执行pytho setup.py develop能成功

**Comment by yuantn** [comment]
Please refer to [here](https://github.com/open-mmlab/mmdetection/issues/2613) or more Issues under mmdetection.

---

请参考 [这里](https://github.com/open-mmlab/mmdetection/issues/2613) 或 mmdetection 下的更多相关问题。
