### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Speng-bjtu** [yuantn/MI-AOD#6]
hello, I want to run your code,but when i scanner" ./script.sh $0''，there is not any reaction,I fellow your instructions before ,I do not kown why?

(active_learn) root@interactive49465:/opt/data/private/ps/workspace/MI-AOD# ./script.sh $0
(active_learn) root@interactive49465:/opt/data/private/ps/workspace/MI-AOD#

**Comment by yuantn** [comment]
When you run the bash file "script.sh", the code is executed in the background. You can view the output log by running this command in the root directory:

`vim log_nohup/nohup_0.log`

Or, if you want to directly output the running log in the foreground, you can run the following command in the code root directory:

`tools/dist_train.sh configs/MIAOD.py 1`

Before each run, please modify the PORT in Line 5 of tools/dist_train.sh to a five-digit port number, which is different from the last run.
