### ISSUE TITLE
Custom Dataset 

### ISSUE THREAD

**Issue by abhigoku10** [yuantn/MI-AOD#64]
@yuantn  thanks for sharing the source code , 
Requirement: I have a sample of 1k annotated dataset of the bounding box for the person  i want to use  MIAOD for labeling remaining 8k image dataset , what process should i follow to annotate the remaining dataset.

Please share ur thoughts Thanks in advance

**Comment by yuantn** [comment]
Thanks for your attention to our work.

You can use the 1k samples as the labeled set and the remaining 8k samples as the unlabeled set. And set 0.5k samples to be selected and labeled for each active learning cycle, then you can know which samples to select.

**Comment by abhigoku10** [comment]
@yuantn  so the 0.5k samples will be annotated accordingly right , the data should be provided in the same VOC format / COCO format ? what is the code changes that has to be performed

**Comment by yuantn** [comment]
The data should be provided in the same VOC format.

Most of the code does not need to change, only the configuration files need.

**Comment by chiran7** [comment]
Dear Author,
Can you suggest a proper change in the configuration file for custom data? although it trains and converges the loss function, I am getting 0 detections (no predictions) on custom data for MIAOD_SSD.

**Comment by yuantn** [comment]
Sorry, I am not clear about your custom dataset. Please describe the error in detail.
