### ISSUE TITLE
How to resume from file

### ISSUE THREAD

**Issue by yozoral** [yuantn/MI-AOD#65]
Hi thank you for this great project. Can you give some instructions on how to resume the training process at specific cycle from model file if it paused in the middle? I changed the config 'resume_from' and it got optimizer loading issue, `ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group`
Even if I commented the optimizer loading, it will stuck and do no training.
Thank you so much if you can give some instructions on this.

**Comment by yuantn** [comment]
Considering that we have modified the detector architecture and training pipeline, we suggest you resume from checkpoints by modifing Line 107-114 and Line 133-135 in `tools/train.py`, as mentioned in part `pth file` in section [`Results of README.md`](https://github.com/yuantn/MI-AOD#results).
