### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'total_epochs'

### ISSUE THREAD

**Issue by sharp-xiang** [yuantn/MI-AOD#68]
运行代码出现这个错误

**Comment by yuantn** [comment]
请提供输出日志。

---

Please provide the output log.

**Comment by sharp-xiang** [comment]
[20220424_113549.log](https://github.com/yuantn/MI-AOD/files/8548982/20220424_113549.log)

**Comment by yuantn** [comment]
这个日志文件中没有包含你说的这个错误信息，请提供完整的报错日志。

---

This log file does not contain the error you reported, please provide the complete error reporting log.
