### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'param_lambda'

### ISSUE THREAD

**Issue by xiaosa96** [yuantn/MI-AOD#7]
Hello, when I run dist_test.sh with the command: bash tools/dist_test.sh work_dirs/MIAL/20210316_092453/latest.pth 4 or run the file test.py using vscode。There are AttributeError: 'NoneType' object has no attribute 'param_lambda'  error 。 I would like to ask you how I can solve this error。 My Torch version is 1.5 and TorchVision is 0.6.0 and MMCV version is 1.0.5

**Comment by yuantn** [comment]
Thanks for the issue!
I have fixed bugs in `tools/test.py` and `mmdet/models/dense_heads/MIAOD_head.py`, you can update these two files and try it again.

**Comment by xiaosa96** [comment]
> Thanks for the issue!
> I have fixed bugs in `tools/test.py` and `mmdet/models/dense_heads/MIAOD_head.py`, you can update these two files and try it again.

Thank you for your reply! I will try again on this problem later. In addition to this, I would like to ask you one more small problem: when I run the training file using the command: bash  ./tools/dist_train.sh  ./configs/ MIAOD.py  4, it will be prompted with StopIteration after several epochs, causing the training to break. I would like to ask if you have any other solutions to this problem (besides using a single GPU).

**Comment by yuantn** [comment]
> > Thanks for the issue!
> > I have fixed bugs in `tools/test.py` and `mmdet/models/dense_heads/MIAOD_head.py`, you can update these two files and try it again.
> 
> Thank you for your reply! I will try again on this problem later. In addition to this, I would like to ask you one more small problem: when I run the training file using the command: bash ./tools/dist_train.sh ./configs/ MIAOD.py 4, it will be prompted with StopIteration after several epochs, causing the training to break. I would like to ask if you have any other solutions to this problem (besides using a single GPU).

This problem does exist when using multiple GPUs, but we haven't figured out the reason now. There is currently no solution available other than using a single GPU.

**Comment by xiaosa96** [comment]
> > > Thanks for the issue!
> > > I have fixed bugs in `tools/test.py` and `mmdet/models/dense_heads/MIAOD_head.py`, you can update these two files and try it again.
> > 
> > 
> > Thank you for your reply! I will try again on this problem later. In addition to this, I would like to ask you one more small problem: when I run the training file using the command: bash ./tools/dist_train.sh ./configs/ MIAOD.py 4, it will be prompted with StopIteration after several epochs, causing the training to break. I would like to ask if you have any other solutions to this problem (besides using a single GPU).
> 
> This problem does exist when using multiple GPUs, but we haven't figured out the reason now. There is currently no solution available other than using a single GPU.

OK, thank you for your reply! Thank you very much for your answers to my questions!

**Comment by yuantn** [comment]
> 
> 
> > Thanks for the issue!
> > I have fixed bugs in `tools/test.py` and `mmdet/models/dense_heads/MIAOD_head.py`, you can update these two files and try it again.
> 
> Thank you for your reply! I will try again on this problem later. In addition to this, I would like to ask you one more small problem: when I run the training file using the command: bash ./tools/dist_train.sh ./configs/ MIAOD.py 4, it will be prompted with StopIteration after several epochs, causing the training to break. I would like to ask if you have any other solutions to this problem (besides using a single GPU).

Hi, I don't know if you have already solved this problem, but someone has provided a possible solution [here](./11). It may be helpful to you.
