### ISSUE TITLE
将代码迁移到其它基于mmdetection框架的程序中

### ISSUE THREAD

**Issue by GuangqianGuo** [yuantn/MI-AOD#75]
作者，您好：
我想问一下，您在mmdetection上的改动有多少。我如果把您的MI-AOD方法迁移到其它基于mmdection框架的程序中工作量有多大？
因为想在其他任务上实验您的方法。
期待您的回复。
谢谢。

**Comment by yuantn** [comment]
你好，改动部分可以参见说明文档中的 [代码结构](../blob/master/README_cn.md#代码结构) 部分。

---

Hello, for the modified codes, please refer to the [Code Structure](../../MI-AOD#code-structure) in the README.md.
