### ISSUE TITLE
RuntimeError: SigmoidFocalLoss is not compiled with GPU support

### ISSUE THREAD

**Issue by zhang-jiali** [yuantn/MI-AOD#76]
您好！我在研读您的论文代码时，运行出现了问题，很长时间都没能解决，麻烦您指点一下。
环境配置都是按照您的readme文件配置的，只是把cuda的版本换成了10.1.因为cuda10.2的环境下我无法安装mmcv-full1.0.5版本。环境配置完成，运行python tools/train.py configs/MIAOD.py 进行训练时，出现RuntimeError: SigmoidFocalLoss is not compiled with GPU support问题，尝试了网上的一些方案还是没有得到解决，希望您能指点一下，感谢感谢！

**Comment by yuantn** [comment]
你好，请尝试用同样的方法配置 [mmDetection v2.3.0 版本](https://github.com/open-mmlab/mmdetection/tree/v2.3.0)，看一下是否会有同样的问题。

---

Hi, please try to configure [mmDetection v2.3.0](https://github.com/open-mmlab/mmdetection/tree/v2.3.0) in the same way and see if you have the same problem.
