### ISSUE TITLE
Very basic doubt about definition of a symbol  

### ISSUE THREAD

**Issue by skbhat** [yuantn/MI-AOD#78]
Namaste,

I would like to know how $y_c^{cls}$ is computed for an image.  It is not described in the paper.  I assume that if an object belonging to category $c$ exists in the image then $y_c^{cls}=1$, else $y_c^{cls}=0$.  Is that correct?

thanks and regards
Srikrishna.

**Comment by yuantn** [comment]
Namaste,

$y^{cls}_c$ is just what you assumed, and it is from the dataset annotation. For example, if there is some objects that belong to the 3-rd class and the 5-th class. The original annotation may be [2,4], and the corresponding $y^{cls}$ is a one-hot vector [0,0,1,0,1].

Best regards,
Tianning Yuan.
