### ISSUE TITLE
I have some questions about “Minimizing Instance Uncertainty to align the distributions of the labeled and unlabeled instances”

### ISSUE THREAD

**Issue by jingtingxu369** [yuantn/MI-AOD#8]
![image](https://user-images.githubusercontent.com/46559128/115411036-b808b480-a225-11eb-8516-445f75910149.png)

**Comment by yuantn** [comment]
Hi, I think that there are some problems in your derivation and analysis:

1. `theta_g` and `theta_f1/2` are non-linear, so the step 4 is not reasonable.

2. There is indeed a feature vector, which can make loss=0.

3. Minimizing the distribution bias is achieved by TWO steps (maximizing AND minimizing uncertainty, as shown in Fig. 2(a) ) but not only minimizing uncertainty. The reduction of bias is achieved in such an iterative process but not a single step.
