### ISSUE TITLE
Tabale 1 : How accuracy of random sample selection is influenced by IUL and IUR

### ISSUE THREAD

**Issue by skbhat** [yuantn/MI-AOD#80]
Namaste,

In Table 1 of the paper is shown below.

![image](https://user-images.githubusercontent.com/8628054/184396743-5db0acab-c513-440c-a138-b6d608999206.png)

As per my understanding, random sample selection is just selecting random training images from the remaining set without using any uncertainty scores.  How does IUL or IUR influence the accuracy of random selection?

thanks and regards
skbhat

**Comment by yuantn** [comment]
Namaste,

Please refer to [here](./4#issuecomment-800871469) for explanation.

Best regards,
Tianning Yuan
