### ISSUE TITLE
RuntimeError: SigmoidFocalLoss is not compiled with GPU support

### ISSUE THREAD

**Issue by chiran7** [yuantn/MI-AOD#82]
Dear Author,

after command : python tools/train.py configs/MIAOD.py, It shows the following error:
 File "/home/cshah/.local/lib/python3.8/site-packages/mmcv/ops/focal_loss.py", line 54, in forward
    ext_module.sigmoid_focal_loss_forward(
RuntimeError: SigmoidFocalLoss is not compiled with GPU support.

I have installed mmcv and mmdetection. Can you suggest the better solution to resolve this issue ?

Thank you for your time and consideration.

**Comment by yuantn** [comment]
Please refer to Issue #81, and __READ IT CAREFULLY__.
