### ISSUE TITLE
No detection of testing of custom train model

### ISSUE THREAD

**Issue by chiran7** [yuantn/MI-AOD#84]
Dear Author,

I have attached the training log on custom data (converted in pascal VOC format). 
![image](https://user-images.githubusercontent.com/25559452/189215855-e77e0505-3fd6-43f4-82f9-b518fbfcc0cc.png)

It gives good results on pascal VOC. However, it does not provide class-wise detection results 'cls_dets' on custom data. 

I checked the return result of single_gpu_test, (y_head), which is used as cls_det  to calculate mean_ap. In the detection results, it shows 0 to dets column. Can you suggest the better solution ?

Thank you for your time and consideration.

**Comment by chiran7** [comment]
#64 , #44, 
Dear Author,
Can you suggest a proper change in the configuration file for custom data? although it trains and converges the loss function, I am getting 0 detections (no predictions) on custom data for MIAOD_SSD, while testing..

**Comment by yuantn** [comment]
Sorry, I am not clear about your custom dataset. Please describe the error in detail.

**Comment by chiran7** [comment]
> Sorry, I am not clear about your custom dataset. Please describe the error in detail.

![image](https://user-images.githubusercontent.com/25559452/190187300-20ea0598-80dd-4b4c-a6ff-4ee4bc808cca.png)


I have attached the screenshot of the test on MIAOD_SSD. In mmdet info, it shows dets  = 0 for most of the classes except class = 20 (where dets = 509800) (in VOC, it has 20 classes, it may be the reason it is showing at class = 20). However, in my custom data, it has more classes. I changed the names of classes in voc.py, and in class_names.py. I changed data into voc format and use only VOC2007 in active_datasets.py. 

Moreover, in your repository, i found that the configuration for VOC and COCO is different. You are using --eval bbox for coco, but using --eval mAP in VOC. Will --eval mAP work on custom data that is converted in VOC format ?

In training, it shows as it is converging with different types of losses, but it is not working for test(as dets column is 0 for all classes except class =20).

I will be grateful if you can suggest a better solution.

Thank you for your time and consideration.

**Comment by yuantn** [comment]
`—eval mAP` can work on all custom data converted in VOC format.

In your custom dataset, what are the 22 classes? What is special about that class with 509800 detection boxes compared to other classes?

Also, have you tested your custom dataset on other general detectors (like RetinaNet and SSD) before, and how well does it work?

**Comment by chiran7** [comment]
> `--eval mAP` can work on all custom data converted in VOC format.
> 
> In your custom dataset, what are the 22 classes? What is special about that class with 509800 detection boxes compared to other classes?
> 
> Also, have you tested your custom dataset on other general detectors (like RetinaNet and SSD) before, and how well does it work?

Thank you for your response. I tried with another custom data that has 30 classes. The issue was same. It shows high detection boxes at class 20 and 0 at others. detection on general detectors like SSD is good. I am trying to see if I can get good detection on SSD (using only first initial labels set training of current active learning cycle). If it works, I can try for whole active learning cycle later.

**Comment by yuantn** [comment]
OK.

What I mean is that, what types are these classes belong to? For example, they may be cats, dogs or cars.

And what is special for class 20? For example, it may be small cups, and they are small objects.

**Comment by chiran7** [comment]
> OK.
> 
> What I mean is that, what types are these classes belong to? For example, they may be cats, dogs or cars.
> 
> And what is special for class 20? For example, it may be small cups, and they are small objects.

thank you for your response. the classes belong to different crops of agriculture (for instance, grass, tree, etc ) and class 20 is just one of the categories indicating crop type. In both custom datasets, the class 20 detection box becomes high ( i think it may be because of the total 20 classes in VOC and there is something missing in configuration). I just replaced the class names in voc.py with custom data classes and used the total class number 30 instead of 20. will mmdetection make all GT class zero for custom data assuming them as empty GT if used inside voc.py? should I use custom data in mmdet instead of just using voc.py with customized class names?

Thank you for your time and consideration.

**Comment by yuantn** [comment]
Please ensure that you have prepared the dataset and code as described [here](https://github.com/open-mmlab/mmdetection/blob/v2.3.0/docs/tutorials/new_dataset.md).
