### ISSUE TITLE
Using mmdetection to test checkpoint file get 0 in mAP

### ISSUE THREAD

**Issue by wonbul2022** [yuantn/MI-AOD#85]
python ./tools/test.py configs/ssd/ssd300_voc.py work_dirs/epoch_5.pth --eval mAP
![image](https://user-images.githubusercontent.com/113097105/194683950-6612fd90-f2e7-40dc-b61f-00887e96122a.png)

**Comment by yuantn** [comment]
Can you provide your corresponding training log?
