### ISSUE TITLE
Unable  to solve error of version.

### ISSUE THREAD

**Issue by Arjunvankani** [yuantn/MI-AOD#87]
I am trying to install dependencies from [https://github.com/yuantn/MI-AOD/blob/master/docs/installation.md](url).
But problem is there, mmcv==1.0.5 is older so many error occurs, and compatible of mmdet version didn't finout. 
Request to you, please help me to find out solution for this.
Please guide me how to setup and run code. With appreciate mmdet , mmcv , mmcv-full code.

**Comment by yuantn** [comment]
Please refer to [here](https://github.com/open-mmlab/mmdetection/blob/v2.3.0/docs/install.md) if you meet any problem on installation. It is the original base repository.

**Comment by Arjunvankani** [comment]
![image](https://user-images.githubusercontent.com/65284186/220568674-e404271e-e6ee-49bb-8277-931addf42833.png)

2023-02-22 14:15:41,624 - mmdet - INFO - Set random seed to 666, deterministic: False
Traceback (most recent call last):
  File "tools/train.py", line 257, in <module>
    main()
  File "tools/train.py", line 105, in main
    X_L, X_U, X_all, all_anns = get_X_L_0(cfg)
NameError: name 'get_X_L_0' is not defined

**Comment by yuantn** [comment]
Please ensure that you have finished the Step 5 in the [Environment Installation Section](https://github.com/yuantn/MI-AOD/blob/master/docs/installation.md#environment-installation).
