### ISSUE TITLE
BDD100K下进行测试

### ISSUE THREAD

**Issue by nanfei666** [yuantn/MI-AOD#89]
非常感谢你的工作，请问我在BDD100K数据集中，随机了5000张图片作为训练集，剩下的64863张图片作为unlabel的图片，epoch ratio设置为[25,1]，epoch为2，X_L_repeat = 2，X_U_repeat = 2，使用了六张GPU训练，lr调整为5e-3，每轮添加5000张图片，最后每一轮的map为0.36，0.39，0.40.涨幅并不明显，请问我的参数设置是否有不合适的地方。

**Comment by nanfei666** [comment]
@yuantn 你好，我将训练改成了单张GPU，降低了batchsize，降低了epoch为[3,1]后，训练得到的第一轮和第二轮分别为0.27, 0.34，涨幅看起来还可以，不过我觉得是因为较低的训练轮数导致模型还没完全训练到位，请问应该怎么设置使用才比较合理呢

**Comment by yuantn** [comment]
你可以与同等实验设置下随机挑选样本的基线实验对比一下，我没有在 BDD100K 数据集上进行过实验。

---

You can compare it with a baseline experiment with randomly sampling under the same experimental settings. I have not tried on the BDD100K dataset.
