### ISSUE TITLE
document-layout-analysis

### ISSUE THREAD

**Issue by samakos** [yuantn/MI-AOD#93]
hello! and amazing work, do you think that it is possible to use your code for document layout analysis? my main concern is that in each document image there are lot of categories (table,title,author, etc.). Is it feasible?

**Comment by yuantn** [comment]
Hello, thanks for your attention to our work. I have not use my method in document layout analysis, but you may have a try. 

Maybe the document can be regarded as the image, and the title, author and table can be regarded as the instances.
