### ISSUE TITLE
能否只使用代码中的主动学习部分来筛选图片呢

### ISSUE THREAD

**Issue by dust-removal** [yuantn/MI-AOD#95]
你好，我刚看完你的论文，我最近有一个应用场景需要使用主动学习，我想知道能够用你的方法仅仅帮我筛选图片，应该怎么做。

**Comment by yuantn** [comment]
你可以修改 [`mmdet/utils/active_datasets.py`](../blob/master/mmdet/utils/active_datasets.py#L60) 文件中的 `update_X_L` 函数（它在 [`tools/train.py`](../blob/master/tools/train.py#L250) 中被调用），令其返回 `X_S`，此即为每一轮主动学习后筛选出不确定性较高的新增样本。

---

You can modify the `update_X_L` function in [`mmdet/utils/active_datasets.py`](../blob/master/mmdet/utils/active_datasets.py#L60) called by [`tools/train.py`](../blob/master/tools/train.py#L250), make it return `X_S`, which are the new selected samples with higher uncertainty after each cycle of active learning.

**Comment by dust-removal** [comment]
> 你可以修改 [`mmdet/utils/active_datasets.py`](../blob/master/mmdet/utils/active_datasets.py#L60) 文件中的 `update_X_L` 函数（它在 [`tools/train.py`](../blob/master/tools/train.py#L250) 中被调用），令其返回 `X_S`，此即为每一轮主动学习后筛选出不确定性较高的新增样本。
> 
> You can modify the `update_X_L` function in [`mmdet/utils/active_datasets.py`](../blob/master/mmdet/utils/active_datasets.py#L60) called by [`tools/train.py`](../blob/master/tools/train.py#L250), make it return `X_S`, which are the new selected samples with higher uncertainty after each cycle of active learning.

感谢，我现在发现mmdet2.3.0已经有了支持windows的版本，那是不是在win上运行就有可能了

**Comment by yuantn** [comment]
是的，但我没有尝试过，你可以试一下。

---

Yes, but I have not tried it. You may have a try.
